# Generated by Django 5.1.1 on 2024-09-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('PE', 'Personal'), ('ER', 'Errand'), ('WO', 'Work'), ('HO', 'Home')], default='PE', max_length=2),
        ),
    ]
