# Generated by Django 5.1.1 on 2024-09-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('Personal', 'personal'), ('Errand', 'errand'), ('Work', 'work'), ('Home', 'home')], default='Personal', max_length=8),
        ),
    ]
